baseURL = 'https://goisra.dev/'
languageCode = 'us'
title = 'Israel Jesús'
theme = 'PaperMod'

[markup.goldmark.renderer]
  unsafe = true

[imaging]
  quality = 100
  resampleFilter = "lanczos"
  anchor = "smart"

[menu]

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Talks"
    url = "/talks"
    weight = 2

  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 3


[permalinks]
  posts = "/:section/:year/:slug"

[params]
  author = "Israel Jesús"
  defaultTheme = "light"
  displayFullLangName = true

  [params.profileMode]
    enabled = true
    title = "Israel Jesús"
    subtitle = "Site Reliability Engineer (SRE) @"
    imageUrl = "/images/pic_redes.jpg"
    imageWidth = 150
    imageHeight = 150

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/goisra"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/goisra"
  [[params.socialIcons]]
    name = "instagram"
    url = "https://www.instagram.com/goisra.dev"
  [[params.socialIcons]]
    name = "youtube"
    url = "https://www.youtube.com/@goisra.CloudLab"
  [[params.socialIcons]]
    name = "gmail"
    url = "mailto:contacto@goisra.dev?subject=Desde Web Site:?body=Hola%20Jes%C3%BAs, "

